// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: favorite.sql

package db

import (
	"context"
)

const addFavorite = `-- name: AddFavorite :one
INSERT INTO favorites (student_id, property_id)
VALUES ($1, $2)
    RETURNING student_id, property_id
`

type AddFavoriteParams struct {
	StudentID  int32 `json:"student_id"`
	PropertyID int32 `json:"property_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, addFavorite, arg.StudentID, arg.PropertyID)
	var i Favorite
	err := row.Scan(&i.StudentID, &i.PropertyID)
	return i, err
}

const getFavoritesApartments = `-- name: GetFavoritesApartments :many
SELECT p.id, p.agent_id, p.title, p.description, p.price, p.location, p.property_type, p.image_url, p.video_url, p.created_at, p.updated_at
FROM properties p
         JOIN favorites f ON f.property_id = p.id
WHERE f.student_id = $1
ORDER BY p.created_at DESC
    LIMIT $2 OFFSET $3
`

type GetFavoritesApartmentsParams struct {
	StudentID int32 `json:"student_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) GetFavoritesApartments(ctx context.Context, arg GetFavoritesApartmentsParams) ([]Property, error) {
	rows, err := q.db.Query(ctx, getFavoritesApartments, arg.StudentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Property
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Location,
			&i.PropertyType,
			&i.ImageUrl,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE student_id = $1 AND property_id = $2
`

type RemoveFavoriteParams struct {
	StudentID  int32 `json:"student_id"`
	PropertyID int32 `json:"property_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.StudentID, arg.PropertyID)
	return err
}
