// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inspection_request.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInspectionRequest = `-- name: CreateInspectionRequest :one
INSERT INTO inspection_requests (
    property_id, student_id, requested_date
) VALUES (
             $1, $2, $3
         )
    RETURNING id, property_id, student_id, status, requested_date, created_at
`

type CreateInspectionRequestParams struct {
	PropertyID    int32            `json:"property_id"`
	StudentID     int32            `json:"student_id"`
	RequestedDate pgtype.Timestamp `json:"requested_date"`
}

func (q *Queries) CreateInspectionRequest(ctx context.Context, arg CreateInspectionRequestParams) (InspectionRequest, error) {
	row := q.db.QueryRow(ctx, createInspectionRequest, arg.PropertyID, arg.StudentID, arg.RequestedDate)
	var i InspectionRequest
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.StudentID,
		&i.Status,
		&i.RequestedDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInspectionRequest = `-- name: DeleteInspectionRequest :exec
DELETE FROM inspection_requests
WHERE id = $1
`

func (q *Queries) DeleteInspectionRequest(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteInspectionRequest, id)
	return err
}

const getInspectionRequest = `-- name: GetInspectionRequest :one
SELECT id, property_id, student_id, status, requested_date, created_at FROM inspection_requests
WHERE id = $1
`

func (q *Queries) GetInspectionRequest(ctx context.Context, id int32) (InspectionRequest, error) {
	row := q.db.QueryRow(ctx, getInspectionRequest, id)
	var i InspectionRequest
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.StudentID,
		&i.Status,
		&i.RequestedDate,
		&i.CreatedAt,
	)
	return i, err
}

const listInspections = `-- name: ListInspections :many
SELECT id, property_id, student_id, status, requested_date, created_at FROM inspection_requests
ORDER BY created_at DESC
    LIMIT $1
OFFSET $2
`

type ListInspectionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInspections(ctx context.Context, arg ListInspectionsParams) ([]InspectionRequest, error) {
	rows, err := q.db.Query(ctx, listInspections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InspectionRequest
	for rows.Next() {
		var i InspectionRequest
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.StudentID,
			&i.Status,
			&i.RequestedDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
