// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Favorite struct {
	StudentID  int32 `json:"student_id"`
	PropertyID int32 `json:"property_id"`
}

type InspectionRequest struct {
	ID            int32            `json:"id"`
	PropertyID    int32            `json:"property_id"`
	StudentID     int32            `json:"student_id"`
	Status        pgtype.Text      `json:"status"`
	RequestedDate pgtype.Timestamp `json:"requested_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Property struct {
	ID           int32            `json:"id"`
	AgentID      pgtype.Int4      `json:"agent_id"`
	Title        string           `json:"title"`
	Description  pgtype.Text      `json:"description"`
	Price        int32            `json:"price"`
	Location     string           `json:"location"`
	PropertyType pgtype.Text      `json:"property_type"`
	ImageUrl     pgtype.Text      `json:"image_url"`
	VideoUrl     pgtype.Text      `json:"video_url"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Review struct {
	ID        int32            `json:"id"`
	StudentID int32            `json:"student_id"`
	Rating    pgtype.Int4      `json:"rating"`
	Comment   pgtype.Text      `json:"comment"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID           pgtype.UUID      `json:"id"`
	RefreshToken string           `json:"refresh_token"`
	UserID       int32            `json:"user_id"`
	UserAgent    string           `json:"user_agent"`
	ClientIp     string           `json:"client_ip"`
	IsBlocked    bool             `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID              int32            `json:"id"`
	FullName        string           `json:"full_name"`
	Email           string           `json:"email"`
	PhoneNumber     string           `json:"phone_number"`
	PasswordHash    string           `json:"password_hash"`
	Role            string           `json:"role"`
	IsEmailVerified bool             `json:"is_email_verified"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type VerifyEmail struct {
	ID        int64            `json:"id"`
	UserID    int32            `json:"user_id"`
	Email     string           `json:"email"`
	Token     string           `json:"token"`
	IsUsed    bool             `json:"is_used"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
