// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: property.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (
    agent_id, title, description, price, location, property_type, image_url, video_url
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8
         )
    RETURNING id, agent_id, title, description, price, location, property_type, image_url, video_url, created_at, updated_at
`

type CreatePropertyParams struct {
	AgentID      pgtype.Int4 `json:"agent_id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	Price        int32       `json:"price"`
	Location     string      `json:"location"`
	PropertyType pgtype.Text `json:"property_type"`
	ImageUrl     pgtype.Text `json:"image_url"`
	VideoUrl     pgtype.Text `json:"video_url"`
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, createProperty,
		arg.AgentID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Location,
		arg.PropertyType,
		arg.ImageUrl,
		arg.VideoUrl,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Location,
		&i.PropertyType,
		&i.ImageUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProperty = `-- name: DeleteProperty :exec
DELETE FROM properties
WHERE id = $1
`

func (q *Queries) DeleteProperty(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProperty, id)
	return err
}

const getProperty = `-- name: GetProperty :one
SELECT id, agent_id, title, description, price, location, property_type, image_url, video_url, created_at, updated_at FROM properties
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProperty(ctx context.Context, id int32) (Property, error) {
	row := q.db.QueryRow(ctx, getProperty, id)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Location,
		&i.PropertyType,
		&i.ImageUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProperties = `-- name: ListProperties :many
SELECT id, agent_id, title, description, price, location, property_type, image_url, video_url, created_at, updated_at FROM properties
ORDER BY created_at DESC
    LIMIT $1
OFFSET $2
`

type ListPropertiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProperties(ctx context.Context, arg ListPropertiesParams) ([]Property, error) {
	rows, err := q.db.Query(ctx, listProperties, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Property
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Location,
			&i.PropertyType,
			&i.ImageUrl,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProperty = `-- name: UpdateProperty :one
UPDATE properties
SET title = $2,
    description = $3,
    price = $4,
    location = $5,
    property_type = $6,
    image_url = $7,
    video_url = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    RETURNING id, agent_id, title, description, price, location, property_type, image_url, video_url, created_at, updated_at
`

type UpdatePropertyParams struct {
	ID           int32       `json:"id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	Price        int32       `json:"price"`
	Location     string      `json:"location"`
	PropertyType pgtype.Text `json:"property_type"`
	ImageUrl     pgtype.Text `json:"image_url"`
	VideoUrl     pgtype.Text `json:"video_url"`
}

func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, updateProperty,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Location,
		arg.PropertyType,
		arg.ImageUrl,
		arg.VideoUrl,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Location,
		&i.PropertyType,
		&i.ImageUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
