// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) (Favorite, error)
	BlockRefreshToken(ctx context.Context, id pgtype.UUID) error
	CreateInspectionRequest(ctx context.Context, arg CreateInspectionRequestParams) (InspectionRequest, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (Session, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteInspectionRequest(ctx context.Context, id int32) error
	DeleteProperty(ctx context.Context, id int32) error
	DeleteReview(ctx context.Context, id int32) error
	GetFavoritesApartments(ctx context.Context, arg GetFavoritesApartmentsParams) ([]Property, error)
	GetInspectionRequest(ctx context.Context, id int32) (InspectionRequest, error)
	GetProperty(ctx context.Context, id int32) (Property, error)
	GetRefreshToken(ctx context.Context, id pgtype.UUID) (Session, error)
	GetReviewByID(ctx context.Context, id int32) (Review, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListInspections(ctx context.Context, arg ListInspectionsParams) ([]InspectionRequest, error)
	ListProperties(ctx context.Context, arg ListPropertiesParams) ([]Property, error)
	ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error)
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error
	UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error)
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
