// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockRefreshToken = `-- name: BlockRefreshToken :exec
UPDATE sessions
SET is_blocked = TRUE
WHERE id = $1
`

func (q *Queries) BlockRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, blockRefreshToken, id)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO sessions (
    id,
    refresh_token,
    user_id,
    user_agent,
    client_ip,
    is_blocked,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, refresh_token, user_id, user_agent, client_ip, is_blocked, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	ID           pgtype.UUID      `json:"id"`
	RefreshToken string           `json:"refresh_token"`
	UserID       int32            `json:"user_id"`
	UserAgent    string           `json:"user_agent"`
	ClientIp     string           `json:"client_ip"`
	IsBlocked    bool             `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (Session, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.RefreshToken,
		arg.UserID,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.UserID,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, refresh_token, user_id, user_agent, client_ip, is_blocked, expires_at, created_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.UserID,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
