// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: verify_email.sql

package db

import (
	"context"
)

const createVerifyEmail = `-- name: CreateVerifyEmail :one
INSERT INTO verify_emails (
     user_id,
     email,
     token
) VALUES (
          $1, $2, $3
         ) RETURNING id, user_id, email, token, is_used, expires_at, created_at
`

type CreateVerifyEmailParams struct {
	UserID int32  `json:"user_id"`
	Email  string `json:"email"`
	Token  string `json:"token"`
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRow(ctx, createVerifyEmail, arg.UserID, arg.Email, arg.Token)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Token,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
